### ISSUE TITLE
Modification of Webtools Geocoding Endpoint - Action needed

### ISSUE THREAD

**Issue by alexboss** [openeuropa/webtools-geocoding-provider#16]
Dear colleagues,

We'd like to inform you that the Webtools Geocoding has been updated to provide results:
* from FOSS (Photon, Nominatim)
* managed and hosted by Eurostat GISCO services https://webgate.ec.europa.eu/fpfis/wikis/display/GISCO/Geocoding+Services 

In a nutshell:
* Webtools Geocoding service has been updated this week to geocode with free in-house Eurostat GISCO Photon provider, instead of the external paying ArcGIS provider
* This works well for services using the supported / official Webtools Geocoding endpoint with a Webtools wrapper
* However, Webtools Geocoding also provides an unofficial endpoint to bypass the Webtools wrapper and return the raw response from the provider - this unofficial endpoint comes with a warning on the wiki: "The "Direct request to service provider" functionality is provided as is for testing purposes. It is not safe nor reliable to build a service or feature over this functionality. Webtools can at anytime, and without prior notice, disable this feature. Also, no caching of results is made, consequently, response times can be long when requesting directly to the service provider."
* The Open Europa Drupal module "webtools geocoding provider" relies on this unofficial endpoint
* Since the default provider is now Eurostat GISCO Photon and not ArcGIS, the Open Europa Drupal module "webtools geocoding provider" won't cope with the new type of response and could be broken

Proposed solutions:
1. If you want to keep ArcGIS as a Geocoding Provider to deal with the same kind of server response, you'll have to subscribe to a paying plan and query their service directly (for instance https://geocode.arcgis.com/arcgis/rest/services/World/GeocodeServer/find?f=json&text=via+giulio+salvadori+20%2C+Rome%2C+Italy&maxLocations=5&outFields= ) - **Standard ESRI  /ArcGIS response**.
1. If you don't mind switching from ArcGIS to Photon, then you'll have to adapt the module to cope with the new sort of server response. If you plan to continue querying directly the service provider, you can actually ditch the Webtools endpoint and directly use the endpoint provided by EUROSTAT GISCO, see available endpoints on https://webgate.ec.europa.eu/fpfis/wikis/display/GISCO/Geocoding+Services - **Standard Photon / Standard Nominatim response**.
1. If you want Webtools to handle the geocoding request, the module will also have to be adapted to cope with the required expected parameters, and also parse the Webtools wrapped response. More information on https://webgate.ec.europa.eu/fpfis/wikis/display/webtools/Geocoding+-+Technical+details - **Custom - tailored-made Webtools / Non standard response**

In all cases, the endpoint used in this module will no longer work as it is now, by the **end of November**:

`const ENDPOINT_URL = 'https://europa.eu/webtools/rest/geocoding/?f=json&text=%s&maxLocations=%d&outFields=*';`

Do you think you'll be able to cope with the changed before end of November?

Thank you and best regards.

Alexandre - DIGIT WEBTOOLS

**Comment by claudiu-cristea** [comment]
@alexboss we're looking into this. BTW, I cannot access the https://webgate.ec.europa.eu/fpfis/wikis/display/GISCO/Geocoding+Services page you've provided

**Comment by claudiu-cristea** [comment]
[Webtools Geocoding provider for Geocoder PHP](https://github.com/openeuropa/webtools-geocoding-provider) is abandoned in favour of [GISCO Geocoding Provider for Geocoder PHP](https://github.com/openeuropa/gisco-geocoding-provider). A Drupal module, using [GISCO Geocoding Provider for Geocoder PHP](https://github.com/openeuropa/gisco-geocoding-provider), is available here https://github.com/openeuropa/oe_gisco_geocoding, but the initial code (PR https://github.com/openeuropa/oe_gisco_geocoding/pull/1) is still not committed yet.

Closing this as resolved.
